version: 2.1
jobs:
  build:
    docker:
# Use the same Docker base as the project
    - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps: # a collection of executable commands making up the 'build' job
      - checkout # pulls source code to the working directory

      - restore_cache: # **restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run**
          key: 
          - v1-dependencies-{{ checksum "requirements.txt" }}
      - run: # install and activate virtual environment with pip
          command: |
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache: # ** special step to save dependency cache **
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ./venv
      - run:
        name: run lint
        command: |
          . venv/bin/activate
          make lint 
